services:
  mysql:
    container_name: mysql
    build:
      context: ./mysql
      args:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql/mysql-data:/var/lib/mysql
    networks:
      - spring-microservice

  auth-service:
    container_name: auth-service
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - mysql
      - eureka-server
    networks:
      - spring-microservice
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/microservice?createDatabaseIfNotExist=true&characterEncoding=UTF-8&serverTimeZone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Hung21052004@
      SPRING_APPLICATION_NAME: auth-service
      LOG_DIR: /app/logs
    volumes:
      - ./logs:/app/logs

  cart-service:
    container_name: cart-service
    build:
      context: ./cart-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - mysql
      - eureka-server
    networks:
      - spring-microservice
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/microservice?createDatabaseIfNotExist=true&characterEncoding=UTF-8&serverTimeZone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Hung21052004@
      SPRING_APPLICATION_NAME: cart-service
      LOG_DIR: /app/logs
    volumes:
      - ./logs:/app/logs

  category-service:
    container_name: category-service
    build:
      context: ./category-service
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      - mysql
      - eureka-server
    networks:
      - spring-microservice
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/microservice?createDatabaseIfNotExist=true&characterEncoding=UTF-8&serverTimeZone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Hung21052004@
      SPRING_APPLICATION_NAME: category-service
      LOG_DIR: /app/logs
    volumes:
      - ./logs:/app/logs

  comment-service:
    container_name: comment-service
    build:
      context: ./comment-service
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    depends_on:
      - mysql
      - eureka-server
    networks:
      - spring-microservice
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/microservice?createDatabaseIfNotExist=true&characterEncoding=UTF-8&serverTimeZone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Hung21052004@
      SPRING_APPLICATION_NAME: comment-service
      LOG_DIR: /app/logs
    volumes:
      - ./logs:/app/logs

  order-service:
    container_name: order-service
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
    depends_on:
      - mysql
      - eureka-server
    networks:
      - spring-microservice
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/microservice?createDatabaseIfNotExist=true&characterEncoding=UTF-8&serverTimeZone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Hung21052004@
      SPRING_APPLICATION_NAME: order-service
      LOG_DIR: /app/logs
    volumes:
      - ./logs:/app/logs


  post-service:
    container_name: post-service
    build:
      context: ./post-service
      dockerfile: Dockerfile
    ports:
      - "8087:8087"
    depends_on:
      - mysql
      - eureka-server
    networks:
      - spring-microservice
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/microservice?createDatabaseIfNotExist=true&characterEncoding=UTF-8&serverTimeZone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Hung21052004@
      SPRING_APPLICATION_NAME: post-service
      LOG_DIR: /app/logs
    volumes:
      - ./logs:/app/logs

  product-service:
    container_name: product-service
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    depends_on:
      - mysql
      - eureka-server
    networks:
      - spring-microservice
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/microservice?createDatabaseIfNotExist=true&characterEncoding=UTF-8&serverTimeZone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Hung21052004@
      SPRING_APPLICATION_NAME: product-service
      LOG_DIR: /app/logs
    volumes:
      - ./logs:/app/logs

  user-service:
    container_name: user-service
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    depends_on:
      - mysql
      - eureka-server
    networks:
      - spring-microservice
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/microservice?createDatabaseIfNotExist=true&characterEncoding=UTF-8&serverTimeZone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Hung21052004@
      SPRING_APPLICATION_NAME: user-service
      LOG_DIR: /app/logs
    volumes:
      - ./logs:/app/logs


  eureka-server:
    container_name: eureka-server
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8761:8761"
    networks:
      - spring-microservice

  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8762:8762"
    depends_on:
      - eureka-server
    networks:
      - spring-microservice
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/

  config-service:
    container_name: config-service
    build:
      context: ./config-service
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8763:8763"
    depends_on:
      - eureka-server
    networks:
      - spring-microservice
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    container_name: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false  # Disable security for development
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elk-stack/elastic-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - spring-microservice

  logstash:
    image: docker.elastic.co/logstash/logstash:8.10.0
    container_name: logstash
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"
      - "9600:9600"
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - ./logs:/app/logs
    networks:
      - spring-microservice

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.4.3
    restart: always
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - spring-microservice

networks:
  spring-microservice:
    driver: bridge